name: CI

on: push

jobs:
  lint_md:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          file-path: './README.md'
